Exemplo dos Slides:

In [1]:
nomes = ["Tupã", "Campinas"]

for nome in nomes:
    print(nome.upper())

    if nome == "Tupã":
        print(f"Olá, {nome}")

TUPÃ
Olá, Tupã
CAMPINAS


In [2]:
x = 10

In [3]:
x ** 2

100

## Listas e Dicionários
*Em Python*, além dos tipos básicos comuns como inteiros e strings, podemos usar por padrão estruturas mais complexas como listas e dicionários:

In [4]:
anos = [2012, 2013, 2014, 2015, 2016]

In [5]:
print(anos)

[2012, 2013, 2014, 2015, 2016]


Usando uma sintaxe própria conhecida como _list comprehension_, podemos facilmente criar uma lista com base em outra

In [6]:
anos_dobrados = [2 * ano for ano in anos]

In [7]:
anos_dobrados

[4024, 4026, 4028, 4030, 4032]

E filtrar uma lista:

In [8]:
anos_pares = [ano for ano in anos if ano % 2 == 0]

In [9]:
anos_pares

[2012, 2014, 2016]

Dicionários, diferente de listas, nos permitem armazenar chaves associadas à valores. Em outras linguagens eles podem ser conhecidos como "maps" ou "hash maps":

In [10]:
info = {
    "nome": "bidu",
    "idade": 28,
    "cidade": "campinas",
    "usa_android": True,
    "livros_na_mesa": ["Refatoração", "Leaving Las Vegas", "Python Fluente"]
}

Assim como no primeiro exemplo, podemos fazer uma iteração sobre um dicionário:

In [11]:
for key in info:
    print(key)

nome
idade
cidade
usa_android
livros_na_mesa


Além da iteração padrão, por chaves, podemos fazer uma iteração por chaves e valores:

In [12]:
list(info.items())

[('nome', 'bidu'),
 ('idade', 28),
 ('cidade', 'campinas'),
 ('usa_android', True),
 ('livros_na_mesa', ['Refatoração', 'Leaving Las Vegas', 'Python Fluente'])]

In [14]:
for a, b in info.items():
    print(f"O valor de {a} é {b}")

O valor de nome é bidu
O valor de idade é 28
O valor de cidade é campinas
O valor de usa_android é True
O valor de livros_na_mesa é ['Refatoração', 'Leaving Las Vegas', 'Python Fluente']


## Conjuntos

In [15]:
b = {1, 3, 4, 5, 3}

In [16]:
b

{1, 3, 4, 5}

In [17]:
a = {1, 2, 4}

In [18]:
b - a

{3, 5}

In [19]:
a - b

{2}

In [20]:
b.issubset(a)

False

## Classes 

In [21]:
class Circle:
    def __init__(self, radius):
        self.radius = radius

In [22]:
c = Circle(12)

In [23]:
c.radius

12

## E o perímetro?

In [24]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    def get_perimeter(self):
        return self.radius * 2 * math.pi

In [25]:
c = Circle(10)

In [26]:
c.get_perimeter()

62.83185307179586

In [27]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius

    @property    
    def perimeter(self):
        return self.radius * 2 * math.pi

In [28]:
c = Circle(10)

In [29]:
c.perimeter

62.83185307179586

In [30]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius

In [31]:
c = Circle(10)

In [32]:
c.perimeter

62.83185307179586

## E Para Mudar o Perímetro?

In [33]:
import math

class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, value):
        self.radius = value / (2 * math.pi)

In [34]:
c = Circle(10)

In [35]:
c.perimeter

62.83185307179586

In [36]:
c.perimeter = 20

In [37]:
c.radius

3.183098861837907

In [38]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)

In [39]:
c = Circle(1)

In [40]:
c.perimeter

6.283185307179586

In [41]:
c.perimeter = 62.83

In [42]:
c.radius

9.999705074463783

## E se eu quero igualar círculos?

Suponha que eu queiro dizer que dois círculos são iguais se os raios forem iguais

In [43]:
c1 = Circle(10)

In [44]:
c2 = Circle(10)

In [45]:
c1 == c2

False

In [50]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)
        
    def __eq__(self, other):
        return self.radius == other.radius

In [51]:
c1 = Circle(10)

In [52]:
c2 = Circle(10)

In [53]:
c1 == c2

True

## Comparar Círculos Maiores?

In [54]:
c1 = Circle(10)

In [55]:
c2 = Circle(20)

In [56]:
c1 > c2

TypeError: '>' not supported between instances of 'Circle' and 'Circle'

In [57]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)
        
    def __eq__(self, other):
        return self.radius == other.radius
    
    def __gt__(self, other):
        return self.radius > other.radius

In [58]:
c1 = Circle(10)

In [59]:
c2 = Circle(20)

In [61]:
c1 > c2

False

In [62]:
c2 > c1

True

## Debugando Círculos!

In [63]:
c1 = Circle(10)

In [64]:
c1

In [65]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)
        
    def __eq__(self, other):
        return self.radius == other.radius
    
    def __gt__(self, other):
        return self.radius > other.radius
    
    def __repr__(self):
        return f"<Circle: radius={self.radius}>"


In [66]:
c1 = Circle(10)

In [67]:
c1

<Circle: radius=10>

In [68]:
c1.perimeter = 20

In [69]:
c1

<Circle: radius=3.183098861837907>

## Usuários Não São Programadores!

In [70]:
print(c1)

<Circle: radius=3.183098861837907>


In [71]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)
        
    def __eq__(self, other):
        return self.radius == other.radius
    
    def __gt__(self, other):
        return self.radius > other.radius
    
    def __repr__(self):
        return f"<Circle: radius={self.radius}>"
    
    def __str__(self):
        return f"<Circle: radius={self.radius:.2f}>"

In [72]:
c1 = Circle(10)

In [73]:
c1.perimeter = 34

In [74]:
c1.radius

5.411268065124442

In [75]:
print(c1)

<Circle: radius=5.41>


## Somando Círculos!

In [76]:
c1 = Circle(10)

In [77]:
c2 = Circle(20)

In [78]:
c1 + c2

TypeError: unsupported operand type(s) for +: 'Circle' and 'Circle'

In [79]:
import math
class Circle:
    def __init__(self, radius):
        self.radius = radius
        
    @property
    def perimeter(self):
        return 2 * math.pi * self.radius
    
    @perimeter.setter
    def perimeter(self, p):
        self.radius = p / (2*math.pi)
        
    def __eq__(self, other):
        return self.radius == other.radius
    
    def __gt__(self, other):
        return self.radius > other.radius
    
    def __repr__(self):
        return f"<Circle: radius={self.radius}>"
    
    def __str__(self):
        return f"Círculo com raio = {self.radius:.2f}"
    
    def __add__(self, other):
        return Circle(self.radius + other.radius)

In [80]:
c1 = Circle(10)

In [81]:
c2 = Circle(20)

In [82]:
c1 + c2

<Circle: radius=30>

# Operações com Numpy

In [83]:
import numpy as np

In [84]:
a = [1, 2, 3]

In [85]:
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [86]:
a = np.array(a)

In [87]:
a 

array([1, 2, 3])

In [88]:
a * 3

array([3, 6, 9])

In [89]:
a + 4

array([5, 6, 7])

In [90]:
mask = a > 1

In [91]:
a[mask]

array([2, 3])